# MAIN FUNCTION GENERATED BY GPT-5.1 

import oracledb

HOST = "vsgate-s1.dei.isep.ipp.pt"
PORT = 10969
USER = "system"
PASSWORD = "oracle"

SERVICE_NAME = "XE"


def main():
    dsn = oracledb.makedsn(HOST, PORT, service_name=SERVICE_NAME)

    print("Trying to connect to:", dsn)

    try:
        with oracledb.connect(user=USER, password=PASSWORD, dsn=dsn) as conn:
            print("Connected!")
            with conn.cursor() as cur:
                cur.execute("SELECT 'OK' AS status, SYSDATE AS now FROM dual")
                row = cur.fetchone()
                print("Test query result:", row)
    except Exception as e:
        print("Connection failed:")
        print(e)


if __name__ == "__main__":
    main()
